name: 'car_sales_dashboard'
version: '1.0.0'
config-version: 2

profile: 'car_sales_dashboard'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  de_project:
    staging:
      +materialized: view
    marts:
      +materialized: table
    intermediate:
      +materialized: view