car_sales_dashboard:
  target: dev
  outputs:
    dev:
      type: postgres
      host: main-db
      user: main
      password: main123
      port: 5432
      dbname: main
      schema: dev
      threads: 1