version: 2

models:
  - name: int_src_customers_cleaned
    description: Table containing customer information.
    columns:
      - name: customer_id
        description: Primary key for the customer list.
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('int_src_sales_condensed')
              field: customer_id

      - name: first_name
        description: First name of the customer.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

      - name: last_name
        description: Last name of the customer.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

      - name: drivers_license
        description: Driver's License of the customer
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      
      - name: mobile_number
        description: Mobile number of the customer.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric

      - name: customer_email
        description: Personal e-mail of the customer.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

      - name: customer_street
        description: Street of the customer's registered residence.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      
      - name: customer_city
        description: City of the customer's registered residence.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

      - name: customer_province
        description: Province of the customer's registered residence.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

      - name: updated_at
        description: Last update of the customer details.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date

  - name: int_src_vehicles_cleaned
    description: Table containing vehicles sold.
    columns:
      - name: vehicle_id
        description: Primary key for the vehicles list.
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('int_src_sales_condensed')
              field: vehicle_id      

      - name: brand_name
        description: Brand of the vehicle.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

      - name: model_name
        description: Model of the vehicle.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

      - name: price
        description: Retail price of the vehicle at the time of purchase.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric

      - name: transmission
        description: Transmission of the vehicle.
        tests:
          - accepted_values:
              values: ['AT', 'MT']
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

      - name: updated_at
        description: Last update of the vehicle details.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date

  - name: int_src_sales_condensed
    description: Condensed table based from stg_src__values.
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: ref('stg_src__values')
    columns:
      - name: transaction_id
        description: Transaction record number for the vehicle purchase.
        tests:
          - unique
          - dbt_expectations.expect_column_values_to_be_increasing:
              sort_column: transaction_id
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint

      - name: purchase_date
        description: Purchase date of the vehicle.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date

      - name: customer_id
        description: Unique ID for the customer.
        tests:
          - not_null

      - name: vehicle_id
        description: Unique ID for the vehicle.
        tests:
          - not_null

      - name: color
        description: Color of the vehicle purchased.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

      - name: plate_number
        description: Designated number plate for the vehicle purchased.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text

      - name: bank
        description: Bank of the buyer used to purchase the vehicle. Can be in-house financing within the dealership as well.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text        

      - name: terms_months
        description: Number of months the buyer availed from the bank to pay for the vehicle in installments.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer        